/*      */package com.parzivail.pswm.structures;

/*      */
/*      *//*      */
import java.util.Random;

/*      */
import net.minecraft.block.Block;
/*      */
import net.minecraft.init.Blocks;
/*      */
import net.minecraft.world.World;
/*      */
import net.minecraft.world.chunk.IChunkProvider;
/*      */
import net.minecraft.world.gen.feature.WorldGenerator;
import cpw.mods.fml.common.IWorldGenerator;

/*      */
/*      */public class WorldGenHut
/*      */extends WorldGenerator
/*      */implements IWorldGenerator
/*      */
{
	/*      */
	/*      */@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkProvider chunkGenerator, IChunkProvider chunkProvider)
	{
	}

	/*      */
	/*      */
	/*      */
	/*      */@Override
	public boolean generate(World world, Random rand, int i, int j, int k)
	/*      */
	{
		if (!this.locationIsValidSpawn(world, i, j, k) || !this.locationIsValidSpawn(world, i + 13, j, k) || !this.locationIsValidSpawn(world, i + 13, j, k + 15) || !this.locationIsValidSpawn(world, i, j, k + 15))
			return false;
		/*      */
		/*      */
		k -= 10;
		i -= 10;
		/*      */
		this.setBlock(world, i + 0, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 0, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 0, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 0, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 1, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 1, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 1, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 2, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 1, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 0, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 0, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 1, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 1, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 2, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 2, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 2, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 2, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 2, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 3, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 3, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 3, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 2, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 10, Blocks.chest, 2);
		this.setBlock(world, i + 3, j + 0, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 4, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 4, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 4, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 3, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 4, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 4, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 4, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 4, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 4, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 4, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 12, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 0, k + 13, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 0, k + 14, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 12, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 1, k + 13, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 1, k + 14, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 4, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 4, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 5, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 5, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 5, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 5, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 2, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 2, k + 12, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 2, k + 13, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 2, k + 14, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 4, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 4, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 5, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 5, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 5, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 6, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 2, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 2, k + 12, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 2, k + 13, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 2, k + 14, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 4, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 4, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 5, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 5, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 5, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 7, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 0, k + 12, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 0, k + 13, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 0, k + 14, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 1, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 1, k + 12, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 1, k + 13, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 1, k + 14, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 4, k + 4, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 9, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 4, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 4, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 5, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 5, k + 6, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 5, k + 7, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 5, k + 8, Blocks.sandstone, 0);
		this.setBlock(world, i + 8, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 8, j + 5, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 0, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 1, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 2, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 11, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 2, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 3, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 10, Blocks.sandstone, 0);
		this.setBlock(world, i + 9, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 13, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 14, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 3, k + 15, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 9, j + 4, k + 1, Blocks.air, 0);
		/* 1000 */this.setBlock(world, i + 9, j + 4, k + 2, Blocks.air, 0);
		/* 1001 */this.setBlock(world, i + 9, j + 4, k + 3, Blocks.air, 0);
		/* 1002 */this.setBlock(world, i + 9, j + 4, k + 4, Blocks.sandstone, 0);
		/* 1003 */this.setBlock(world, i + 9, j + 4, k + 5, Blocks.sandstone, 0);
		/* 1004 */this.setBlock(world, i + 9, j + 4, k + 6, Blocks.sandstone, 0);
		/* 1005 */this.setBlock(world, i + 9, j + 4, k + 7, Blocks.sandstone, 0);
		/* 1006 */this.setBlock(world, i + 9, j + 4, k + 8, Blocks.sandstone, 0);
		/* 1007 */this.setBlock(world, i + 9, j + 4, k + 9, Blocks.sandstone, 0);
		/* 1008 */this.setBlock(world, i + 9, j + 4, k + 10, Blocks.air, 0);
		/* 1009 */this.setBlock(world, i + 9, j + 4, k + 11, Blocks.air, 0);
		/* 1010 */this.setBlock(world, i + 9, j + 4, k + 12, Blocks.air, 0);
		/* 1011 */this.setBlock(world, i + 9, j + 4, k + 13, Blocks.air, 0);
		/* 1012 */this.setBlock(world, i + 9, j + 4, k + 14, Blocks.air, 0);
		/* 1013 */this.setBlock(world, i + 9, j + 4, k + 15, Blocks.air, 0);
		/* 1014 */this.setBlock(world, i + 9, j + 5, k + 0, Blocks.air, 0);
		/* 1015 */this.setBlock(world, i + 9, j + 5, k + 1, Blocks.air, 0);
		/* 1016 */this.setBlock(world, i + 9, j + 5, k + 2, Blocks.air, 0);
		/* 1017 */this.setBlock(world, i + 9, j + 5, k + 3, Blocks.air, 0);
		/* 1018 */this.setBlock(world, i + 9, j + 5, k + 4, Blocks.air, 0);
		/* 1019 */this.setBlock(world, i + 9, j + 5, k + 5, Blocks.air, 0);
		/* 1020 */this.setBlock(world, i + 9, j + 5, k + 6, Blocks.air, 0);
		/* 1021 */this.setBlock(world, i + 9, j + 5, k + 7, Blocks.air, 0);
		/* 1022 */this.setBlock(world, i + 9, j + 5, k + 8, Blocks.air, 0);
		/* 1023 */this.setBlock(world, i + 9, j + 5, k + 9, Blocks.air, 0);
		/* 1024 */this.setBlock(world, i + 9, j + 5, k + 10, Blocks.air, 0);
		/* 1025 */this.setBlock(world, i + 9, j + 5, k + 11, Blocks.air, 0);
		/* 1026 */this.setBlock(world, i + 9, j + 5, k + 12, Blocks.air, 0);
		/* 1027 */this.setBlock(world, i + 9, j + 5, k + 13, Blocks.air, 0);
		/* 1028 */this.setBlock(world, i + 9, j + 5, k + 14, Blocks.air, 0);
		/* 1029 */this.setBlock(world, i + 9, j + 5, k + 15, Blocks.air, 0);
		/* 1030 */this.setBlock(world, i + 10, j + 0, k + 0, Blocks.air, 0);
		/* 1031 */this.setBlock(world, i + 10, j + 0, k + 1, Blocks.air, 0);
		/* 1032 */this.setBlock(world, i + 10, j + 0, k + 2, Blocks.sandstone, 0);
		/* 1033 */this.setBlock(world, i + 10, j + 0, k + 3, Blocks.air, 0);
		/* 1034 */this.setBlock(world, i + 10, j + 0, k + 4, Blocks.air, 0);
		/* 1035 */this.setBlock(world, i + 10, j + 0, k + 5, Blocks.air, 0);
		/* 1036 */this.setBlock(world, i + 10, j + 0, k + 6, Blocks.air, 0);
		/* 1037 */this.setBlock(world, i + 10, j + 0, k + 7, Blocks.air, 0);
		/* 1038 */this.setBlock(world, i + 10, j + 0, k + 8, Blocks.air, 0);
		/* 1039 */this.setBlock(world, i + 10, j + 0, k + 9, Blocks.air, 0);
		/* 1040 */this.setBlock(world, i + 10, j + 0, k + 10, Blocks.air, 0);
		/* 1041 */this.setBlock(world, i + 10, j + 0, k + 11, Blocks.sandstone, 0);
		/* 1042 */this.setBlock(world, i + 10, j + 0, k + 12, Blocks.air, 0);
		/* 1043 */this.setBlock(world, i + 10, j + 0, k + 13, Blocks.air, 0);
		/* 1044 */this.setBlock(world, i + 10, j + 0, k + 14, Blocks.air, 0);
		/* 1045 */this.setBlock(world, i + 10, j + 0, k + 15, Blocks.air, 0);
		/* 1046 */this.setBlock(world, i + 10, j + 1, k + 0, Blocks.air, 0);
		/* 1047 */this.setBlock(world, i + 10, j + 1, k + 1, Blocks.air, 0);
		/* 1048 */this.setBlock(world, i + 10, j + 1, k + 2, Blocks.sandstone, 0);
		/* 1049 */this.setBlock(world, i + 10, j + 1, k + 3, Blocks.air, 0);
		/* 1050 */this.setBlock(world, i + 10, j + 1, k + 4, Blocks.air, 0);
		/* 1051 */this.setBlock(world, i + 10, j + 1, k + 5, Blocks.air, 0);
		/* 1052 */this.setBlock(world, i + 10, j + 1, k + 6, Blocks.air, 0);
		/* 1053 */this.setBlock(world, i + 10, j + 1, k + 7, Blocks.air, 0);
		/* 1054 */this.setBlock(world, i + 10, j + 1, k + 8, Blocks.air, 0);
		/* 1055 */this.setBlock(world, i + 10, j + 1, k + 9, Blocks.air, 0);
		/* 1056 */this.setBlock(world, i + 10, j + 1, k + 10, Blocks.air, 0);
		/* 1057 */this.setBlock(world, i + 10, j + 1, k + 11, Blocks.sandstone, 0);
		/* 1058 */this.setBlock(world, i + 10, j + 1, k + 12, Blocks.air, 0);
		/* 1059 */this.setBlock(world, i + 10, j + 1, k + 13, Blocks.air, 0);
		/* 1060 */this.setBlock(world, i + 10, j + 1, k + 14, Blocks.air, 0);
		/* 1061 */this.setBlock(world, i + 10, j + 1, k + 15, Blocks.air, 0);
		/* 1062 */this.setBlock(world, i + 10, j + 2, k + 0, Blocks.air, 0);
		/* 1063 */this.setBlock(world, i + 10, j + 2, k + 1, Blocks.air, 0);
		/* 1064 */this.setBlock(world, i + 10, j + 2, k + 2, Blocks.air, 0);
		/* 1065 */this.setBlock(world, i + 10, j + 2, k + 3, Blocks.sandstone, 0);
		/* 1066 */this.setBlock(world, i + 10, j + 2, k + 5, Blocks.air, 0);
		/* 1067 */this.setBlock(world, i + 10, j + 2, k + 6, Blocks.air, 0);
		/* 1068 */this.setBlock(world, i + 10, j + 2, k + 7, Blocks.air, 0);
		/* 1069 */this.setBlock(world, i + 10, j + 2, k + 8, Blocks.air, 0);
		/* 1070 */this.setBlock(world, i + 10, j + 2, k + 10, Blocks.sandstone, 0);
		/* 1071 */this.setBlock(world, i + 10, j + 2, k + 11, Blocks.air, 0);
		/* 1072 */this.setBlock(world, i + 10, j + 2, k + 12, Blocks.air, 0);
		/* 1073 */this.setBlock(world, i + 10, j + 2, k + 13, Blocks.air, 0);
		/* 1074 */this.setBlock(world, i + 10, j + 2, k + 14, Blocks.air, 0);
		/* 1075 */this.setBlock(world, i + 10, j + 2, k + 15, Blocks.air, 0);
		/* 1076 */this.setBlock(world, i + 10, j + 3, k + 0, Blocks.air, 0);
		/* 1077 */this.setBlock(world, i + 10, j + 3, k + 1, Blocks.air, 0);
		/* 1078 */this.setBlock(world, i + 10, j + 3, k + 2, Blocks.air, 0);
		/* 1079 */this.setBlock(world, i + 10, j + 3, k + 3, Blocks.air, 0);
		/* 1080 */this.setBlock(world, i + 10, j + 3, k + 4, Blocks.sandstone, 0);
		/* 1081 */this.setBlock(world, i + 10, j + 3, k + 5, Blocks.air, 0);
		/* 1082 */this.setBlock(world, i + 10, j + 3, k + 6, Blocks.air, 0);
		/* 1083 */this.setBlock(world, i + 10, j + 3, k + 7, Blocks.air, 0);
		/* 1084 */this.setBlock(world, i + 10, j + 3, k + 8, Blocks.air, 0);
		/* 1085 */this.setBlock(world, i + 10, j + 3, k + 9, Blocks.sandstone, 0);
		/* 1086 */this.setBlock(world, i + 10, j + 3, k + 10, Blocks.air, 0);
		/* 1087 */this.setBlock(world, i + 10, j + 3, k + 11, Blocks.air, 0);
		/* 1088 */this.setBlock(world, i + 10, j + 3, k + 12, Blocks.air, 0);
		/* 1089 */this.setBlock(world, i + 10, j + 3, k + 13, Blocks.air, 0);
		/* 1090 */this.setBlock(world, i + 10, j + 3, k + 14, Blocks.air, 0);
		/* 1091 */this.setBlock(world, i + 10, j + 3, k + 15, Blocks.air, 0);
		/* 1092 */this.setBlock(world, i + 10, j + 4, k + 0, Blocks.air, 0);
		/* 1093 */this.setBlock(world, i + 10, j + 4, k + 1, Blocks.air, 0);
		/* 1094 */this.setBlock(world, i + 10, j + 4, k + 2, Blocks.air, 0);
		/* 1095 */this.setBlock(world, i + 10, j + 4, k + 3, Blocks.air, 0);
		/* 1096 */this.setBlock(world, i + 10, j + 4, k + 4, Blocks.air, 0);
		/* 1097 */this.setBlock(world, i + 10, j + 4, k + 5, Blocks.sandstone, 0);
		/* 1098 */this.setBlock(world, i + 10, j + 4, k + 6, Blocks.sandstone, 0);
		/* 1099 */this.setBlock(world, i + 10, j + 4, k + 7, Blocks.sandstone, 0);
		/* 1100 */this.setBlock(world, i + 10, j + 4, k + 8, Blocks.sandstone, 0);
		/* 1101 */this.setBlock(world, i + 10, j + 4, k + 9, Blocks.air, 0);
		/* 1102 */this.setBlock(world, i + 10, j + 4, k + 10, Blocks.air, 0);
		/* 1103 */this.setBlock(world, i + 10, j + 4, k + 11, Blocks.air, 0);
		/* 1104 */this.setBlock(world, i + 10, j + 4, k + 12, Blocks.air, 0);
		/* 1105 */this.setBlock(world, i + 10, j + 4, k + 13, Blocks.air, 0);
		/* 1106 */this.setBlock(world, i + 10, j + 4, k + 14, Blocks.air, 0);
		/* 1107 */this.setBlock(world, i + 10, j + 4, k + 15, Blocks.air, 0);
		/* 1108 */this.setBlock(world, i + 10, j + 5, k + 0, Blocks.air, 0);
		/* 1109 */this.setBlock(world, i + 10, j + 5, k + 1, Blocks.air, 0);
		/* 1110 */this.setBlock(world, i + 10, j + 5, k + 2, Blocks.air, 0);
		/* 1111 */this.setBlock(world, i + 10, j + 5, k + 3, Blocks.air, 0);
		/* 1112 */this.setBlock(world, i + 10, j + 5, k + 4, Blocks.air, 0);
		/* 1113 */this.setBlock(world, i + 10, j + 5, k + 5, Blocks.air, 0);
		/* 1114 */this.setBlock(world, i + 10, j + 5, k + 6, Blocks.air, 0);
		/* 1115 */this.setBlock(world, i + 10, j + 5, k + 7, Blocks.air, 0);
		/* 1116 */this.setBlock(world, i + 10, j + 5, k + 8, Blocks.air, 0);
		/* 1117 */this.setBlock(world, i + 10, j + 5, k + 9, Blocks.air, 0);
		/* 1118 */this.setBlock(world, i + 10, j + 5, k + 10, Blocks.air, 0);
		/* 1119 */this.setBlock(world, i + 10, j + 5, k + 11, Blocks.air, 0);
		/* 1120 */this.setBlock(world, i + 10, j + 5, k + 12, Blocks.air, 0);
		/* 1121 */this.setBlock(world, i + 10, j + 5, k + 13, Blocks.air, 0);
		/* 1122 */this.setBlock(world, i + 10, j + 5, k + 14, Blocks.air, 0);
		/* 1123 */this.setBlock(world, i + 10, j + 5, k + 15, Blocks.air, 0);
		/* 1124 */this.setBlock(world, i + 11, j + 0, k + 0, Blocks.air, 0);
		/* 1125 */this.setBlock(world, i + 11, j + 0, k + 1, Blocks.air, 0);
		/* 1126 */this.setBlock(world, i + 11, j + 0, k + 2, Blocks.air, 0);
		/* 1127 */this.setBlock(world, i + 11, j + 0, k + 3, Blocks.sandstone, 0);
		/* 1128 */this.setBlock(world, i + 11, j + 0, k + 4, Blocks.sandstone, 0);
		/* 1129 */this.setBlock(world, i + 11, j + 0, k + 5, Blocks.air, 0);
		/* 1130 */this.setBlock(world, i + 11, j + 0, k + 6, Blocks.air, 0);
		/* 1131 */this.setBlock(world, i + 11, j + 0, k + 7, Blocks.air, 0);
		/* 1132 */this.setBlock(world, i + 11, j + 0, k + 8, Blocks.air, 0);
		/* 1133 */this.setBlock(world, i + 11, j + 0, k + 9, Blocks.sandstone, 0);
		/* 1134 */this.setBlock(world, i + 11, j + 0, k + 10, Blocks.sandstone, 0);
		/* 1135 */this.setBlock(world, i + 11, j + 0, k + 11, Blocks.air, 0);
		/* 1136 */this.setBlock(world, i + 11, j + 0, k + 12, Blocks.air, 0);
		/* 1137 */this.setBlock(world, i + 11, j + 0, k + 13, Blocks.air, 0);
		/* 1138 */this.setBlock(world, i + 11, j + 0, k + 14, Blocks.air, 0);
		/* 1139 */this.setBlock(world, i + 11, j + 0, k + 15, Blocks.air, 0);
		/* 1140 */this.setBlock(world, i + 11, j + 1, k + 0, Blocks.air, 0);
		/* 1141 */this.setBlock(world, i + 11, j + 1, k + 1, Blocks.air, 0);
		/* 1142 */this.setBlock(world, i + 11, j + 1, k + 2, Blocks.air, 0);
		/* 1143 */this.setBlock(world, i + 11, j + 1, k + 3, Blocks.sandstone, 0);
		/* 1144 */this.setBlock(world, i + 11, j + 1, k + 4, Blocks.sandstone, 0);
		/* 1145 */this.setBlock(world, i + 11, j + 1, k + 5, Blocks.air, 0);
		/* 1146 */this.setBlock(world, i + 11, j + 1, k + 6, Blocks.air, 0);
		/* 1147 */this.setBlock(world, i + 11, j + 1, k + 7, Blocks.air, 0);
		/* 1148 */this.setBlock(world, i + 11, j + 1, k + 8, Blocks.air, 0);
		/* 1149 */this.setBlock(world, i + 11, j + 1, k + 9, Blocks.sandstone, 0);
		/* 1150 */this.setBlock(world, i + 11, j + 1, k + 10, Blocks.sandstone, 0);
		/* 1151 */this.setBlock(world, i + 11, j + 1, k + 11, Blocks.air, 0);
		/* 1152 */this.setBlock(world, i + 11, j + 1, k + 12, Blocks.air, 0);
		/* 1153 */this.setBlock(world, i + 11, j + 1, k + 13, Blocks.air, 0);
		/* 1154 */this.setBlock(world, i + 11, j + 1, k + 14, Blocks.air, 0);
		/* 1155 */this.setBlock(world, i + 11, j + 1, k + 15, Blocks.air, 0);
		/* 1156 */this.setBlock(world, i + 11, j + 2, k + 0, Blocks.air, 0);
		/* 1157 */this.setBlock(world, i + 11, j + 2, k + 1, Blocks.air, 0);
		/* 1158 */this.setBlock(world, i + 11, j + 2, k + 2, Blocks.air, 0);
		/* 1159 */this.setBlock(world, i + 11, j + 2, k + 3, Blocks.air, 0);
		/* 1160 */this.setBlock(world, i + 11, j + 2, k + 4, Blocks.sandstone, 0);
		/* 1161 */this.setBlock(world, i + 11, j + 2, k + 5, Blocks.sandstone, 0);
		/* 1162 */this.setBlock(world, i + 11, j + 2, k + 6, Blocks.sandstone, 0);
		/* 1163 */this.setBlock(world, i + 11, j + 2, k + 7, Blocks.sandstone, 0);
		/* 1164 */this.setBlock(world, i + 11, j + 2, k + 8, Blocks.sandstone, 0);
		/* 1165 */this.setBlock(world, i + 11, j + 2, k + 9, Blocks.sandstone, 0);
		/* 1166 */this.setBlock(world, i + 11, j + 2, k + 10, Blocks.air, 0);
		/* 1167 */this.setBlock(world, i + 11, j + 2, k + 11, Blocks.air, 0);
		/* 1168 */this.setBlock(world, i + 11, j + 2, k + 12, Blocks.air, 0);
		/* 1169 */this.setBlock(world, i + 11, j + 2, k + 13, Blocks.air, 0);
		/* 1170 */this.setBlock(world, i + 11, j + 2, k + 14, Blocks.air, 0);
		/* 1171 */this.setBlock(world, i + 11, j + 2, k + 15, Blocks.air, 0);
		/* 1172 */this.setBlock(world, i + 11, j + 3, k + 0, Blocks.air, 0);
		/* 1173 */this.setBlock(world, i + 11, j + 3, k + 1, Blocks.air, 0);
		/* 1174 */this.setBlock(world, i + 11, j + 3, k + 2, Blocks.air, 0);
		/* 1175 */this.setBlock(world, i + 11, j + 3, k + 3, Blocks.air, 0);
		/* 1176 */this.setBlock(world, i + 11, j + 3, k + 4, Blocks.air, 0);
		/* 1177 */this.setBlock(world, i + 11, j + 3, k + 5, Blocks.sandstone, 0);
		/* 1178 */this.setBlock(world, i + 11, j + 3, k + 6, Blocks.sandstone, 0);
		/* 1179 */this.setBlock(world, i + 11, j + 3, k + 7, Blocks.sandstone, 0);
		/* 1180 */this.setBlock(world, i + 11, j + 3, k + 8, Blocks.sandstone, 0);
		/* 1181 */this.setBlock(world, i + 11, j + 3, k + 9, Blocks.air, 0);
		/* 1182 */this.setBlock(world, i + 11, j + 3, k + 10, Blocks.air, 0);
		/* 1183 */this.setBlock(world, i + 11, j + 3, k + 11, Blocks.air, 0);
		/* 1184 */this.setBlock(world, i + 11, j + 3, k + 12, Blocks.air, 0);
		/* 1185 */this.setBlock(world, i + 11, j + 3, k + 13, Blocks.air, 0);
		/* 1186 */this.setBlock(world, i + 11, j + 3, k + 14, Blocks.air, 0);
		/* 1187 */this.setBlock(world, i + 11, j + 3, k + 15, Blocks.air, 0);
		/* 1188 */this.setBlock(world, i + 11, j + 4, k + 0, Blocks.air, 0);
		/* 1189 */this.setBlock(world, i + 11, j + 4, k + 1, Blocks.air, 0);
		/* 1190 */this.setBlock(world, i + 11, j + 4, k + 2, Blocks.air, 0);
		/* 1191 */this.setBlock(world, i + 11, j + 4, k + 3, Blocks.air, 0);
		/* 1192 */this.setBlock(world, i + 11, j + 4, k + 4, Blocks.air, 0);
		/* 1193 */this.setBlock(world, i + 11, j + 4, k + 5, Blocks.air, 0);
		/* 1194 */this.setBlock(world, i + 11, j + 4, k + 6, Blocks.air, 0);
		/* 1195 */this.setBlock(world, i + 11, j + 4, k + 7, Blocks.air, 0);
		/* 1196 */this.setBlock(world, i + 11, j + 4, k + 8, Blocks.air, 0);
		/* 1197 */this.setBlock(world, i + 11, j + 4, k + 9, Blocks.air, 0);
		/* 1198 */this.setBlock(world, i + 11, j + 4, k + 10, Blocks.air, 0);
		/* 1199 */this.setBlock(world, i + 11, j + 4, k + 11, Blocks.air, 0);
		/* 1200 */this.setBlock(world, i + 11, j + 4, k + 12, Blocks.air, 0);
		/* 1201 */this.setBlock(world, i + 11, j + 4, k + 13, Blocks.air, 0);
		/* 1202 */this.setBlock(world, i + 11, j + 4, k + 14, Blocks.air, 0);
		/* 1203 */this.setBlock(world, i + 11, j + 4, k + 15, Blocks.air, 0);
		/* 1204 */this.setBlock(world, i + 11, j + 5, k + 0, Blocks.air, 0);
		/* 1205 */this.setBlock(world, i + 11, j + 5, k + 1, Blocks.air, 0);
		/* 1206 */this.setBlock(world, i + 11, j + 5, k + 2, Blocks.air, 0);
		/* 1207 */this.setBlock(world, i + 11, j + 5, k + 3, Blocks.air, 0);
		/* 1208 */this.setBlock(world, i + 11, j + 5, k + 4, Blocks.air, 0);
		/* 1209 */this.setBlock(world, i + 11, j + 5, k + 5, Blocks.air, 0);
		/* 1210 */this.setBlock(world, i + 11, j + 5, k + 6, Blocks.air, 0);
		/* 1211 */this.setBlock(world, i + 11, j + 5, k + 7, Blocks.air, 0);
		/* 1212 */this.setBlock(world, i + 11, j + 5, k + 8, Blocks.air, 0);
		/* 1213 */this.setBlock(world, i + 11, j + 5, k + 9, Blocks.air, 0);
		/* 1214 */this.setBlock(world, i + 11, j + 5, k + 10, Blocks.air, 0);
		/* 1215 */this.setBlock(world, i + 11, j + 5, k + 11, Blocks.air, 0);
		/* 1216 */this.setBlock(world, i + 11, j + 5, k + 12, Blocks.air, 0);
		/* 1217 */this.setBlock(world, i + 11, j + 5, k + 13, Blocks.air, 0);
		/* 1218 */this.setBlock(world, i + 11, j + 5, k + 14, Blocks.air, 0);
		/* 1219 */this.setBlock(world, i + 11, j + 5, k + 15, Blocks.air, 0);
		/* 1220 */this.setBlock(world, i + 12, j + 0, k + 0, Blocks.air, 0);
		/* 1221 */this.setBlock(world, i + 12, j + 0, k + 1, Blocks.air, 0);
		/* 1222 */this.setBlock(world, i + 12, j + 0, k + 2, Blocks.air, 0);
		/* 1223 */this.setBlock(world, i + 12, j + 0, k + 3, Blocks.air, 0);
		/* 1224 */this.setBlock(world, i + 12, j + 0, k + 4, Blocks.air, 0);
		/* 1225 */this.setBlock(world, i + 12, j + 0, k + 5, Blocks.sandstone, 0);
		/* 1226 */this.setBlock(world, i + 12, j + 0, k + 6, Blocks.sandstone, 0);
		/* 1227 */this.setBlock(world, i + 12, j + 0, k + 7, Blocks.sandstone, 0);
		/* 1228 */this.setBlock(world, i + 12, j + 0, k + 8, Blocks.sandstone, 0);
		/* 1229 */this.setBlock(world, i + 12, j + 0, k + 9, Blocks.air, 0);
		/* 1230 */this.setBlock(world, i + 12, j + 0, k + 10, Blocks.air, 0);
		/* 1231 */this.setBlock(world, i + 12, j + 0, k + 11, Blocks.air, 0);
		/* 1232 */this.setBlock(world, i + 12, j + 0, k + 12, Blocks.air, 0);
		/* 1233 */this.setBlock(world, i + 12, j + 0, k + 13, Blocks.air, 0);
		/* 1234 */this.setBlock(world, i + 12, j + 0, k + 14, Blocks.air, 0);
		/* 1235 */this.setBlock(world, i + 12, j + 0, k + 15, Blocks.air, 0);
		/* 1236 */this.setBlock(world, i + 12, j + 1, k + 0, Blocks.air, 0);
		/* 1237 */this.setBlock(world, i + 12, j + 1, k + 1, Blocks.air, 0);
		/* 1238 */this.setBlock(world, i + 12, j + 1, k + 2, Blocks.air, 0);
		/* 1239 */this.setBlock(world, i + 12, j + 1, k + 3, Blocks.air, 0);
		/* 1240 */this.setBlock(world, i + 12, j + 1, k + 4, Blocks.air, 0);
		/* 1241 */this.setBlock(world, i + 12, j + 1, k + 5, Blocks.sandstone, 0);
		/* 1242 */this.setBlock(world, i + 12, j + 1, k + 6, Blocks.sandstone, 0);
		/* 1243 */this.setBlock(world, i + 12, j + 1, k + 7, Blocks.sandstone, 0);
		/* 1244 */this.setBlock(world, i + 12, j + 1, k + 8, Blocks.sandstone, 0);
		/* 1245 */this.setBlock(world, i + 12, j + 1, k + 9, Blocks.air, 0);
		/* 1246 */this.setBlock(world, i + 12, j + 1, k + 10, Blocks.air, 0);
		/* 1247 */this.setBlock(world, i + 12, j + 1, k + 11, Blocks.air, 0);
		/* 1248 */this.setBlock(world, i + 12, j + 1, k + 12, Blocks.air, 0);
		/* 1249 */this.setBlock(world, i + 12, j + 1, k + 13, Blocks.air, 0);
		/* 1250 */this.setBlock(world, i + 12, j + 1, k + 14, Blocks.air, 0);
		/* 1251 */this.setBlock(world, i + 12, j + 1, k + 15, Blocks.air, 0);
		/* 1252 */this.setBlock(world, i + 12, j + 2, k + 0, Blocks.air, 0);
		/* 1253 */this.setBlock(world, i + 12, j + 2, k + 1, Blocks.air, 0);
		/* 1254 */this.setBlock(world, i + 12, j + 2, k + 2, Blocks.air, 0);
		/* 1255 */this.setBlock(world, i + 12, j + 2, k + 3, Blocks.air, 0);
		/* 1256 */this.setBlock(world, i + 12, j + 2, k + 4, Blocks.air, 0);
		/* 1257 */this.setBlock(world, i + 12, j + 2, k + 5, Blocks.air, 0);
		/* 1258 */this.setBlock(world, i + 12, j + 2, k + 6, Blocks.sandstone, 0);
		/* 1259 */this.setBlock(world, i + 12, j + 2, k + 7, Blocks.sandstone, 0);
		/* 1260 */this.setBlock(world, i + 12, j + 2, k + 8, Blocks.air, 0);
		/* 1261 */this.setBlock(world, i + 12, j + 2, k + 9, Blocks.air, 0);
		/* 1262 */this.setBlock(world, i + 12, j + 2, k + 10, Blocks.air, 0);
		/* 1263 */this.setBlock(world, i + 12, j + 2, k + 11, Blocks.air, 0);
		/* 1264 */this.setBlock(world, i + 12, j + 2, k + 12, Blocks.air, 0);
		/* 1265 */this.setBlock(world, i + 12, j + 2, k + 13, Blocks.air, 0);
		/* 1266 */this.setBlock(world, i + 12, j + 2, k + 14, Blocks.air, 0);
		/* 1267 */this.setBlock(world, i + 12, j + 2, k + 15, Blocks.air, 0);
		/* 1268 */this.setBlock(world, i + 12, j + 3, k + 0, Blocks.air, 0);
		/* 1269 */this.setBlock(world, i + 12, j + 3, k + 1, Blocks.air, 0);
		/* 1270 */this.setBlock(world, i + 12, j + 3, k + 2, Blocks.air, 0);
		/* 1271 */this.setBlock(world, i + 12, j + 3, k + 3, Blocks.air, 0);
		/* 1272 */this.setBlock(world, i + 12, j + 3, k + 4, Blocks.air, 0);
		/* 1273 */this.setBlock(world, i + 12, j + 3, k + 5, Blocks.air, 0);
		/* 1274 */this.setBlock(world, i + 12, j + 3, k + 6, Blocks.air, 0);
		/* 1275 */this.setBlock(world, i + 12, j + 3, k + 7, Blocks.air, 0);
		/* 1276 */this.setBlock(world, i + 12, j + 3, k + 8, Blocks.air, 0);
		/* 1277 */this.setBlock(world, i + 12, j + 3, k + 9, Blocks.air, 0);
		/* 1278 */this.setBlock(world, i + 12, j + 3, k + 10, Blocks.air, 0);
		/* 1279 */this.setBlock(world, i + 12, j + 3, k + 11, Blocks.air, 0);
		/* 1280 */this.setBlock(world, i + 12, j + 3, k + 12, Blocks.air, 0);
		/* 1281 */this.setBlock(world, i + 12, j + 3, k + 13, Blocks.air, 0);
		/* 1282 */this.setBlock(world, i + 12, j + 3, k + 14, Blocks.air, 0);
		/* 1283 */this.setBlock(world, i + 12, j + 3, k + 15, Blocks.air, 0);
		/* 1284 */this.setBlock(world, i + 12, j + 4, k + 0, Blocks.air, 0);
		/* 1285 */this.setBlock(world, i + 12, j + 4, k + 1, Blocks.air, 0);
		/* 1286 */this.setBlock(world, i + 12, j + 4, k + 2, Blocks.air, 0);
		/* 1287 */this.setBlock(world, i + 12, j + 4, k + 3, Blocks.air, 0);
		/* 1288 */this.setBlock(world, i + 12, j + 4, k + 4, Blocks.air, 0);
		/* 1289 */this.setBlock(world, i + 12, j + 4, k + 5, Blocks.air, 0);
		/* 1290 */this.setBlock(world, i + 12, j + 4, k + 6, Blocks.air, 0);
		/* 1291 */this.setBlock(world, i + 12, j + 4, k + 7, Blocks.air, 0);
		/* 1292 */this.setBlock(world, i + 12, j + 4, k + 8, Blocks.air, 0);
		/* 1293 */this.setBlock(world, i + 12, j + 4, k + 9, Blocks.air, 0);
		/* 1294 */this.setBlock(world, i + 12, j + 4, k + 10, Blocks.air, 0);
		/* 1295 */this.setBlock(world, i + 12, j + 4, k + 11, Blocks.air, 0);
		/* 1296 */this.setBlock(world, i + 12, j + 4, k + 12, Blocks.air, 0);
		/* 1297 */this.setBlock(world, i + 12, j + 4, k + 13, Blocks.air, 0);
		/* 1298 */this.setBlock(world, i + 12, j + 4, k + 14, Blocks.air, 0);
		/* 1299 */this.setBlock(world, i + 12, j + 4, k + 15, Blocks.air, 0);
		/* 1300 */this.setBlock(world, i + 12, j + 5, k + 0, Blocks.air, 0);
		/* 1301 */this.setBlock(world, i + 12, j + 5, k + 1, Blocks.air, 0);
		/* 1302 */this.setBlock(world, i + 12, j + 5, k + 2, Blocks.air, 0);
		/* 1303 */this.setBlock(world, i + 12, j + 5, k + 3, Blocks.air, 0);
		/* 1304 */this.setBlock(world, i + 12, j + 5, k + 4, Blocks.air, 0);
		/* 1305 */this.setBlock(world, i + 12, j + 5, k + 5, Blocks.air, 0);
		/* 1306 */this.setBlock(world, i + 12, j + 5, k + 6, Blocks.air, 0);
		/* 1307 */this.setBlock(world, i + 12, j + 5, k + 7, Blocks.air, 0);
		/* 1308 */this.setBlock(world, i + 12, j + 5, k + 8, Blocks.air, 0);
		/* 1309 */this.setBlock(world, i + 12, j + 5, k + 9, Blocks.air, 0);
		/* 1310 */this.setBlock(world, i + 12, j + 5, k + 10, Blocks.air, 0);
		/* 1311 */this.setBlock(world, i + 12, j + 5, k + 11, Blocks.air, 0);
		/* 1312 */this.setBlock(world, i + 12, j + 5, k + 12, Blocks.air, 0);
		/* 1313 */this.setBlock(world, i + 12, j + 5, k + 13, Blocks.air, 0);
		/* 1314 */this.setBlock(world, i + 12, j + 5, k + 14, Blocks.air, 0);
		/* 1315 */this.setBlock(world, i + 12, j + 5, k + 15, Blocks.air, 0);
		/* 1316 */this.setBlock(world, i + 13, j + 0, k + 0, Blocks.air, 0);
		/* 1317 */this.setBlock(world, i + 13, j + 0, k + 1, Blocks.air, 0);
		/* 1318 */this.setBlock(world, i + 13, j + 0, k + 2, Blocks.air, 0);
		/* 1319 */this.setBlock(world, i + 13, j + 0, k + 3, Blocks.air, 0);
		/* 1320 */this.setBlock(world, i + 13, j + 0, k + 4, Blocks.air, 0);
		/* 1321 */this.setBlock(world, i + 13, j + 0, k + 5, Blocks.air, 0);
		/* 1322 */this.setBlock(world, i + 13, j + 0, k + 6, Blocks.air, 0);
		/* 1323 */this.setBlock(world, i + 13, j + 0, k + 7, Blocks.air, 0);
		/* 1324 */this.setBlock(world, i + 13, j + 0, k + 8, Blocks.air, 0);
		/* 1325 */this.setBlock(world, i + 13, j + 0, k + 9, Blocks.air, 0);
		/* 1326 */this.setBlock(world, i + 13, j + 0, k + 10, Blocks.air, 0);
		/* 1327 */this.setBlock(world, i + 13, j + 0, k + 11, Blocks.air, 0);
		/* 1328 */this.setBlock(world, i + 13, j + 0, k + 12, Blocks.air, 0);
		/* 1329 */this.setBlock(world, i + 13, j + 0, k + 13, Blocks.air, 0);
		/* 1330 */this.setBlock(world, i + 13, j + 0, k + 14, Blocks.air, 0);
		/* 1331 */this.setBlock(world, i + 13, j + 0, k + 15, Blocks.air, 0);
		/* 1332 */this.setBlock(world, i + 13, j + 1, k + 0, Blocks.air, 0);
		/* 1333 */this.setBlock(world, i + 13, j + 1, k + 1, Blocks.air, 0);
		/* 1334 */this.setBlock(world, i + 13, j + 1, k + 2, Blocks.air, 0);
		/* 1335 */this.setBlock(world, i + 13, j + 1, k + 3, Blocks.air, 0);
		/* 1336 */this.setBlock(world, i + 13, j + 1, k + 4, Blocks.air, 0);
		/* 1337 */this.setBlock(world, i + 13, j + 1, k + 5, Blocks.air, 0);
		/* 1338 */this.setBlock(world, i + 13, j + 1, k + 6, Blocks.air, 0);
		/* 1339 */this.setBlock(world, i + 13, j + 1, k + 7, Blocks.air, 0);
		/* 1340 */this.setBlock(world, i + 13, j + 1, k + 8, Blocks.air, 0);
		/* 1341 */this.setBlock(world, i + 13, j + 1, k + 9, Blocks.air, 0);
		/* 1342 */this.setBlock(world, i + 13, j + 1, k + 10, Blocks.air, 0);
		/* 1343 */this.setBlock(world, i + 13, j + 1, k + 11, Blocks.air, 0);
		/* 1344 */this.setBlock(world, i + 13, j + 1, k + 12, Blocks.air, 0);
		/* 1345 */this.setBlock(world, i + 13, j + 1, k + 13, Blocks.air, 0);
		/* 1346 */this.setBlock(world, i + 13, j + 1, k + 14, Blocks.air, 0);
		/* 1347 */this.setBlock(world, i + 13, j + 1, k + 15, Blocks.air, 0);
		/* 1348 */this.setBlock(world, i + 13, j + 2, k + 0, Blocks.air, 0);
		/* 1349 */this.setBlock(world, i + 13, j + 2, k + 1, Blocks.air, 0);
		/* 1350 */this.setBlock(world, i + 13, j + 2, k + 2, Blocks.air, 0);
		/* 1351 */this.setBlock(world, i + 13, j + 2, k + 3, Blocks.air, 0);
		/* 1352 */this.setBlock(world, i + 13, j + 2, k + 4, Blocks.air, 0);
		/* 1353 */this.setBlock(world, i + 13, j + 2, k + 5, Blocks.air, 0);
		/* 1354 */this.setBlock(world, i + 13, j + 2, k + 6, Blocks.air, 0);
		/* 1355 */this.setBlock(world, i + 13, j + 2, k + 7, Blocks.air, 0);
		/* 1356 */this.setBlock(world, i + 13, j + 2, k + 8, Blocks.air, 0);
		/* 1357 */this.setBlock(world, i + 13, j + 2, k + 9, Blocks.air, 0);
		/* 1358 */this.setBlock(world, i + 13, j + 2, k + 10, Blocks.air, 0);
		/* 1359 */this.setBlock(world, i + 13, j + 2, k + 11, Blocks.air, 0);
		/* 1360 */this.setBlock(world, i + 13, j + 2, k + 12, Blocks.air, 0);
		/* 1361 */this.setBlock(world, i + 13, j + 2, k + 13, Blocks.air, 0);
		/* 1362 */this.setBlock(world, i + 13, j + 2, k + 14, Blocks.air, 0);
		/* 1363 */this.setBlock(world, i + 13, j + 2, k + 15, Blocks.air, 0);
		/* 1364 */this.setBlock(world, i + 13, j + 3, k + 0, Blocks.air, 0);
		/* 1365 */this.setBlock(world, i + 13, j + 3, k + 1, Blocks.air, 0);
		/* 1366 */this.setBlock(world, i + 13, j + 3, k + 2, Blocks.air, 0);
		/* 1367 */this.setBlock(world, i + 13, j + 3, k + 3, Blocks.air, 0);
		/* 1368 */this.setBlock(world, i + 13, j + 3, k + 4, Blocks.air, 0);
		/* 1369 */this.setBlock(world, i + 13, j + 3, k + 5, Blocks.air, 0);
		/* 1370 */this.setBlock(world, i + 13, j + 3, k + 6, Blocks.air, 0);
		/* 1371 */this.setBlock(world, i + 13, j + 3, k + 7, Blocks.air, 0);
		/* 1372 */this.setBlock(world, i + 13, j + 3, k + 8, Blocks.air, 0);
		/* 1373 */this.setBlock(world, i + 13, j + 3, k + 9, Blocks.air, 0);
		/* 1374 */this.setBlock(world, i + 13, j + 3, k + 10, Blocks.air, 0);
		/* 1375 */this.setBlock(world, i + 13, j + 3, k + 11, Blocks.air, 0);
		/* 1376 */this.setBlock(world, i + 13, j + 3, k + 12, Blocks.air, 0);
		/* 1377 */this.setBlock(world, i + 13, j + 3, k + 13, Blocks.air, 0);
		/* 1378 */this.setBlock(world, i + 13, j + 3, k + 14, Blocks.air, 0);
		/* 1379 */this.setBlock(world, i + 13, j + 3, k + 15, Blocks.air, 0);
		/* 1380 */this.setBlock(world, i + 13, j + 4, k + 0, Blocks.air, 0);
		/* 1381 */this.setBlock(world, i + 13, j + 4, k + 1, Blocks.air, 0);
		/* 1382 */this.setBlock(world, i + 13, j + 4, k + 2, Blocks.air, 0);
		/* 1383 */this.setBlock(world, i + 13, j + 4, k + 3, Blocks.air, 0);
		/* 1384 */this.setBlock(world, i + 13, j + 4, k + 4, Blocks.air, 0);
		/* 1385 */this.setBlock(world, i + 13, j + 4, k + 5, Blocks.air, 0);
		/* 1386 */this.setBlock(world, i + 13, j + 4, k + 6, Blocks.air, 0);
		/* 1387 */this.setBlock(world, i + 13, j + 4, k + 7, Blocks.air, 0);
		/* 1388 */this.setBlock(world, i + 13, j + 4, k + 8, Blocks.air, 0);
		/* 1389 */this.setBlock(world, i + 13, j + 4, k + 9, Blocks.air, 0);
		/* 1390 */this.setBlock(world, i + 13, j + 4, k + 10, Blocks.air, 0);
		/* 1391 */this.setBlock(world, i + 13, j + 4, k + 11, Blocks.air, 0);
		/* 1392 */this.setBlock(world, i + 13, j + 4, k + 12, Blocks.air, 0);
		/* 1393 */this.setBlock(world, i + 13, j + 4, k + 13, Blocks.air, 0);
		/* 1394 */this.setBlock(world, i + 13, j + 4, k + 14, Blocks.air, 0);
		/* 1395 */this.setBlock(world, i + 13, j + 4, k + 15, Blocks.air, 0);
		/* 1396 */this.setBlock(world, i + 13, j + 5, k + 0, Blocks.air, 0);
		/* 1397 */this.setBlock(world, i + 13, j + 5, k + 1, Blocks.air, 0);
		/* 1398 */this.setBlock(world, i + 13, j + 5, k + 2, Blocks.air, 0);
		/* 1399 */this.setBlock(world, i + 13, j + 5, k + 3, Blocks.air, 0);
		/* 1400 */this.setBlock(world, i + 13, j + 5, k + 4, Blocks.air, 0);
		/* 1401 */this.setBlock(world, i + 13, j + 5, k + 5, Blocks.air, 0);
		/* 1402 */this.setBlock(world, i + 13, j + 5, k + 6, Blocks.air, 0);
		/* 1403 */this.setBlock(world, i + 13, j + 5, k + 7, Blocks.air, 0);
		/* 1404 */this.setBlock(world, i + 13, j + 5, k + 8, Blocks.air, 0);
		/* 1405 */this.setBlock(world, i + 13, j + 5, k + 9, Blocks.air, 0);
		/* 1406 */this.setBlock(world, i + 13, j + 5, k + 10, Blocks.air, 0);
		/* 1407 */this.setBlock(world, i + 13, j + 5, k + 11, Blocks.air, 0);
		/* 1408 */this.setBlock(world, i + 13, j + 5, k + 12, Blocks.air, 0);
		/* 1409 */this.setBlock(world, i + 13, j + 5, k + 13, Blocks.air, 0);
		/* 1410 */this.setBlock(world, i + 13, j + 5, k + 14, Blocks.air, 0);
		/* 1411 */this.setBlock(world, i + 13, j + 5, k + 15, Blocks.air, 0);
		/* 1412 */world.setBlockMetadataWithNotify(i + 3, j + 2, k + 4, 3, 2);
		/* 1413 */world.setBlockMetadataWithNotify(i + 3, j + 2, k + 9, 4, 2);
		/* 1414 */world.setBlockMetadataWithNotify(i + 4, j + 2, k + 3, 1, 2);
		/* 1415 */world.setBlockMetadataWithNotify(i + 4, j + 2, k + 10, 1, 2);
		/* 1416 */world.setBlockMetadataWithNotify(i + 5, j + 4, k + 5, 3, 2);
		/* 1417 */world.setBlockMetadataWithNotify(i + 5, j + 4, k + 8, 4, 2);
		/* 1418 */world.setBlockMetadataWithNotify(i + 6, j + 1, k + 13, 1, 2);
		/* 1419 */world.setBlockMetadataWithNotify(i + 7, j + 1, k + 13, 2, 2);
		/* 1420 */world.setBlockMetadataWithNotify(i + 8, j + 4, k + 5, 3, 2);
		/* 1421 */world.setBlockMetadataWithNotify(i + 8, j + 4, k + 8, 4, 2);
		/* 1422 */world.setBlockMetadataWithNotify(i + 9, j + 2, k + 3, 2, 2);
		/* 1423 */world.setBlockMetadataWithNotify(i + 9, j + 2, k + 10, 2, 2);
		/* 1424 */world.setBlockMetadataWithNotify(i + 10, j + 2, k + 4, 3, 2);
		/* 1425 */world.setBlockMetadataWithNotify(i + 10, j + 2, k + 9, 4, 2);
		/*      */
		/* 1427 */return true;
		/*      */}

	/*      */protected Block[] getValidSpawnBlocks()
	/*      */
	{
		return new Block[] { Blocks.sand, Blocks.sandstone };
		/*      */}

	/*      */
	/*      */public boolean locationIsValidSpawn(World world, int i, int j, int k)
	/*      */
	{
		int distanceToAir = 0;
		Block check = world.getBlock(i, j, k);
		/*      */
		while (check != Blocks.air)
		/*      */
		{
			if (distanceToAir > 3)
				return false;
			/*      */
			/*      */
			distanceToAir++;
			check = world.getBlock(i, j + distanceToAir, k);
			/*      */}
		/*      */
		j += distanceToAir - 1;
		/*      */
		Block block = world.getBlock(i, j, k);
		Block blockAbove = world.getBlock(i, j + 1, k);
		Block blockBelow = world.getBlock(i, j - 1, k);
		/*      */
		for (Block x : this.getValidSpawnBlocks())
		/*      */
		{
			if (blockAbove != Blocks.air)
				return false;
			/*      */
			if (block == x)
				return true;
			/*      */
			if (block == Blocks.snow && blockBelow == x)
				return true;
			/*      */}
		/*      */
		return false;
		/*      */}

	/*      */
	/*      */public void setBlock(World world, int x, int y, int z, Block block, int metadata)
	/*      */
	{
		Block b1 = world.getBlock(x, y, z);
		/*      */
		if (b1.isAir(world, x, y, z) || b1.isLeaves(world, x, y, z))
			world.setBlock(x, y, z, block, metadata, 2);
		/*      */}
}
/*
 * Location: C:\Users\Colby\Downloads\Parzi's Star Wars Mod
 * v1.2.0-dev7.jar!\com\parzi\starwarsmod\structures\WorldGenHut.class Java
 * compiler version: 6 (50.0) JD-Core Version: 0.7.1
 */